# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.IntegerField(default=-1),
        ),
    ]
