# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160602_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.IntegerField(default=0),
        ),
    ]
